project:
  type: book
  output-dir: docs  ## only for GitHub publishing

book:
  title: "Dissertation"
  author: "I. M. Awesome"
  date: last-modified
  chapters:
    - index.qmd     ## intro chapter named "index" to facilitate online sharing
    - methods.qmd
    - results.qmd
    - discussion.qmd
    - bibliography.qmd
  reader-mode: false # A toggle that lets the reader hide the left navigation and right table of contents
  output-file: "Dissertation"   # produces Dissertation.pdf

bibliography: references.bib

language: 
  title-block-published: "Last Updated"

format:
  html:
    theme:
      light: flatly      ## change to your preference
      dark: darkly
    include-after-body: # adds hypothesis commenting
      text: |
        <script src="https://hypothes.is/embed.js" async></script>
    other-links:
      - text: Grad Skool format
        icon: file-earmark-pdf      # or file-pdf, download, etc.
        href: /Dissertation.pdf
        target: _blank
  pdf: default



