project:
  type: book
  output-dir: docs  ## only for GitHub publishing

book:
  title: "Dissertation"
  author: "I. M. Awesome"
  date: "date"      ## returns current date
  chapters:
    - index.qmd     ## only for GitHub publishing - rendering to a different named .html
    - methods.qmd
    - results.qmd
    - discussion.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly      ## change to your preference
      dark: darkly
    include-after-body: # adds hypothesis commenting
      text: |
        <script src="https://hypothes.is/embed.js" async></script>



